/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnitest_myapplication_Test */

#ifndef _Included_com_jnitest_myapplication_Test
#define _Included_com_jnitest_myapplication_Test

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnitest_myapplication_Test
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */

jstring Java_com_jnitest_myapplication_Test_getNativeString(JNIEnv *env, jobject obj){
    return (*env)->NewStringUTF(env, "hello from native");
}


#ifdef __cplusplus
}
#endif

#endif
